(() => {
  'use strict';
  const vscode = acquireVsCodeApi();
  const ids = ['errorBanner','errorText','retry','conversationView','conversation','historyView','historyBack','history','composerArea','prompt','modelButton','composerStatus','composerModel','send','modelPicker','modelClose','modelList','agentActivity','changedFiles','workingState','workingLabel','historyButton','moreButton','headerMenu','localOnlyToggle','localOnlyState','toolsButton','toolsMenu','webSearchToggle','webSearchState','searchBadge','askMode','agentMode','contextChips'];
  const el = Object.fromEntries(ids.map(id => [id, document.getElementById(id)]));
  let state = { authenticated:false, busy:false, models:[], sessions:[], localOnly:true, mode:'agent', webSearch:false, contexts:[] };
  let streamingText = '', streamingContent, stickToBottom = true, activeView = 'conversation', agentActive = false;
  const post = (type, data={}) => vscode.postMessage({type, ...data});
  function resetConversation(){streamingText='';streamingContent=undefined;el.conversation.replaceChildren();el.agentActivity.replaceChildren();el.agentActivity.hidden=true;el.changedFiles.replaceChildren();el.changedFiles.hidden=true;el.errorBanner.hidden=true;el.errorBanner.classList.remove('notice');showView('conversation');}
  window.addEventListener('message',event=>{if(event.data?.type==='conversationReset')resetConversation();});
  document.addEventListener('click',event=>{if(event.target===el.newChatButton)post('newChat');});
  const node = (tag, text, className) => { const n=document.createElement(tag); if(className)n.className=className; if(text!==undefined)n.textContent=text; return n; };

  function chatModels(){ return state.models.filter(m=>m.type==='chat'&&m.available&&(!state.localOnly||m.location==='local')); }
  function selectedModel(){ if(state.selectedModelId==='auto'){const local=chatModels().find(m=>m.location==='local');return{id:'auto',name:local?`Auto · ${local.name}`:'Auto',location:local?.location||'auto'};} return state.models.find(m=>m.id===state.selectedModelId)||{id:state.selectedModelId,name:state.selectedModelId||'Auto',location:'unknown'}; }
  function setBusy(value){ state.busy=value; el.send.disabled=!state.authenticated||(!value&&!el.prompt.value.trim()); el.send.textContent=value?'Stop':'↑'; el.send.classList.toggle('stop',value); el.send.title=value?'Stop Carrot':'Send (Enter)'; el.send.setAttribute('aria-label',value?'Stop Carrot':'Send message'); el.prompt.disabled=value||!state.authenticated; el.modelButton.disabled=value||!state.authenticated; el.workingState.hidden=!value; if(value&&!el.workingLabel.textContent)el.workingLabel.textContent='Thinking…'; }
  function autoGrow(){ el.prompt.style.height='auto'; el.prompt.style.height=Math.min(el.prompt.scrollHeight,140)+'px'; el.send.disabled=!state.authenticated||(!state.busy&&!el.prompt.value.trim()); }
  function showView(view){activeView=view;el.conversationView.hidden=view!=='conversation';el.historyView.hidden=view!=='history';el.composerArea.hidden=view!=='conversation'||!state.authenticated;if(view==='history')renderHistory();}

  function renderMarkdown(source){const holder=node('div',undefined,'content');const escaped=String(source).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');const blocks=[];let safe=escaped.replace(/```([a-zA-Z0-9_-]*)\n([\s\S]*?)```/g,(_m,lang,code)=>{const i=blocks.push('<pre><code data-language="'+lang+'">'+code.trim()+'</code></pre>')-1;return '\u0000BLOCK'+i+'\u0000';});safe=safe.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`\n]+)`/g,'<code>$1</code>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" rel="noopener noreferrer">$1</a>').replace(/^(?:- |\* )(.+)$/gm,'<li>$1</li>').replace(/\n{2,}/g,'</p><p>').replace(/\n/g,'<br>');safe='<p>'+safe+'</p>';safe=safe.replace(/<p>\u0000BLOCK(\d+)\u0000<\/p>/g,(_m,i)=>blocks[Number(i)]);holder.innerHTML = safe;holder.querySelectorAll('a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();post('openExternal',{url:a.href});}));holder.querySelectorAll('pre').forEach(pre=>{const copy=node('button','Copy','copy-button');copy.type='button';copy.addEventListener('click',()=>post('copyCode',{code:pre.querySelector('code')?.textContent||''}));pre.prepend(copy);});return holder;}
  function messageNode(role,content,createdAt){const article=node('article',undefined,'message '+role);if(role==='assistant'){article.append(renderMarkdown(content));return article;}const wrap=node('div',undefined,'user-message-wrap');wrap.append(node('div',content,'content'));const actions=node('div',undefined,'message-actions');const time=node('span',formatTime(createdAt),'message-time');const copy=node('button','⧉','message-action'),edit=node('button','✎','message-action'),resend=node('button','↻','message-action');copy.type=edit.type=resend.type='button';copy.title='Copy prompt';edit.title='Edit prompt';resend.title='Resend prompt';copy.setAttribute('aria-label','Copy prompt');edit.setAttribute('aria-label','Edit prompt');resend.setAttribute('aria-label','Resend prompt');copy.addEventListener('click',()=>post('copyCode',{code:content}));edit.addEventListener('click',()=>editPrompt(content));resend.addEventListener('click',()=>send(content));actions.append(time,copy,edit,resend);wrap.append(actions);article.append(wrap);return article;}
  function formatTime(value){const date=value?new Date(value):new Date();return Number.isNaN(date.getTime())?'':date.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});}
  function editPrompt(content){if(state.busy)return;el.prompt.value=content;autoGrow();el.prompt.focus();el.prompt.setSelectionRange(content.length,content.length);}
  function emptyState(){const w=node('div',undefined,'empty-state');w.append(node('div','🥕','empty-icon'),node('h2','What are we building?'),node('p','Ask about your code, debug an issue, or explore this workspace.'));const starters=node('div',undefined,'starters');for(const prompt of ['Explain this project','Find a bug','Improve this code']){const b=node('button',prompt,'starter');b.type='button';b.addEventListener('click',()=>send(prompt));starters.append(b);}w.append(starters);return w;}
  function signInState(){const w=node('div',undefined,'empty-state');w.append(node('div','🥕','empty-icon'),node('h2','Sign in to Carrot AI'),node('p','Use your existing Carrot account to continue.'));const b=node('button','Sign In','starter');b.type='button';b.addEventListener('click',()=>post('signIn'));w.append(b);return w;}
  function renderConversation(force=false){const changed=el.conversation.dataset.sessionId!==(state.sessionId||'');const distance=el.conversation.scrollHeight-el.conversation.scrollTop;el.conversation.dataset.sessionId=state.sessionId||'';el.conversation.replaceChildren();if(!state.authenticated)el.conversation.append(signInState());else{const messages=state.session?.messages?.filter(m=>m.role!=='system')||[];if(!messages.length)el.conversation.append(emptyState());else messages.forEach(m=>el.conversation.append(messageNode(m.role,m.content,m.createdAt)));}if(force||changed||stickToBottom)el.conversation.scrollTop=el.conversation.scrollHeight;else el.conversation.scrollTop=Math.max(0,el.conversation.scrollHeight-distance);}
  function groupForDate(value){const d=new Date(value),now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),yesterday=new Date(today.getTime()-86400000);return d>=today?'Today':d>=yesterday?'Yesterday':'Older';}
  function renderHistory(){el.history.replaceChildren();if(!state.sessions.length){el.history.append(node('div','No previous chats','empty-state'));return;}let last;for(const session of state.sessions){const group=groupForDate(session.updatedAt);if(group!==last){el.history.append(node('div',group,'history-group'));last=group;}const row=node('div',undefined,'history-row'),open=node('button',session.title||'Untitled chat','history-open'),remove=node('button','×','icon-button history-delete');open.type=remove.type='button';open.addEventListener('click',()=>{stickToBottom=true;showView('conversation');post('openSession',{sessionId:session.id});});remove.addEventListener('click',()=>post('deleteSession',{sessionId:session.id}));row.append(open,remove);el.history.append(row);}}
  function renderModels(){el.modelList.replaceChildren();const groups=[['Auto',[{id:'auto',name:'Auto',provider:'Local first',location:'auto'}]],['Local',chatModels().filter(m=>m.location==='local')],['Cloud',chatModels().filter(m=>m.location==='cloud')]];for(const [label,models] of groups){if(!models.length)continue;el.modelList.append(node('div',label,'model-group'));for(const model of models){const b=node('button',undefined,'model-option'+(model.id===state.selectedModelId?' selected':''));b.type='button';b.append(node('span',model.name,'truncate'),node('span',model.provider,'model-meta truncate'));b.addEventListener('click',()=>{el.modelPicker.hidden=true;post('selectModel',{modelId:model.id});});el.modelList.append(b);}}}
  function renderOptions(){el.askMode.classList.toggle('selected',state.mode==='ask');el.agentMode.classList.toggle('selected',state.mode==='agent');el.localOnlyToggle.setAttribute('aria-checked',String(!!state.localOnly));el.localOnlyState.textContent=state.localOnly?'ON':'OFF';el.localOnlyState.classList.toggle('enabled',!!state.localOnly);el.webSearchToggle.setAttribute('aria-checked',String(!!state.webSearch));el.webSearchState.textContent=state.webSearch?'ON':'OFF';el.webSearchState.classList.toggle('enabled',!!state.webSearch);el.searchBadge.hidden=!state.webSearch;el.contextChips.replaceChildren();for(const context of state.contexts||[]){const chip=node('span',undefined,'context-chip');chip.append(node('span',context.label,'truncate'));const remove=node('button','×');remove.type='button';remove.addEventListener('click',()=>post('removeContext',{contextId:context.id}));chip.append(remove);el.contextChips.append(chip);}el.contextChips.hidden=!(state.contexts||[]).length;}
  function renderState(next){const previous=state.sessionId;state={...state,...next};const model=selectedModel(),location=model.location==='cloud'?'Cloud':model.location==='local'?'Local':'Auto';el.composerModel.textContent=model.name+' · '+location;el.composerStatus.classList.toggle('error',!!state.error);el.errorBanner.classList.remove('notice');el.retry.hidden=false;el.errorBanner.hidden=!state.error;el.errorText.textContent=state.status||'Connection unavailable';if(!state.authenticated)showView('conversation');renderConversation(previous!==state.sessionId);if(activeView==='history')renderHistory();renderModels();renderOptions();setBusy(!!state.busy);vscode.setState({sessionId:state.sessionId,activeView});}
  function send(explicit){const prompt=(explicit||el.prompt.value).trim();if(!prompt||state.busy||!state.authenticated)return;el.prompt.value='';autoGrow();stickToBottom=true;post('sendMessage',{prompt,mode:state.mode,webSearch:!!state.webSearch});}

  el.conversation.addEventListener('scroll',()=>{stickToBottom=el.conversation.scrollHeight-el.conversation.scrollTop-el.conversation.clientHeight<60;});el.prompt.addEventListener('input',autoGrow);el.prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});el.send.addEventListener('click',()=>state.busy?post('stopAgent'):send());el.modelButton.addEventListener('click',()=>{renderModels();el.modelPicker.hidden=false;el.modelClose.focus();});el.modelClose.addEventListener('click',()=>{el.modelPicker.hidden=true;el.modelButton.focus();});el.modelPicker.addEventListener('click',e=>{if(e.target===el.modelPicker)el.modelPicker.hidden=true;});el.historyBack.addEventListener('click',()=>showView('conversation'));el.historyButton.addEventListener('click',()=>showView('history'));el.retry.addEventListener('click',()=>post('refreshModels'));
  el.moreButton.addEventListener('click',()=>{el.headerMenu.hidden=!el.headerMenu.hidden;el.toolsMenu.hidden=true;});el.toolsButton.addEventListener('click',()=>{el.toolsMenu.hidden=!el.toolsMenu.hidden;el.toolsButton.setAttribute('aria-expanded',String(!el.toolsMenu.hidden));el.headerMenu.hidden=true;});el.webSearchToggle.addEventListener('click',()=>{state.webSearch=!state.webSearch;renderOptions();post('setWebSearch',{enabled:state.webSearch});});el.askMode.addEventListener('click',()=>{state.mode='ask';renderOptions();});el.agentMode.addEventListener('click',()=>{state.mode='agent';renderOptions();});el.toolsMenu.querySelectorAll('[data-context]').forEach(b=>b.addEventListener('click',()=>{post('addContext',{kind:b.dataset.context});el.toolsMenu.hidden=true;}));el.headerMenu.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.action;el.headerMenu.hidden=true;if(action==='history')showView('history');else if(action==='toggleLocalOnly')post('toggleLocalOnly',{enabled:!state.localOnly});else post(action==='settings'?'openSettings':action);}));
  document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;el.modelPicker.hidden=true;el.headerMenu.hidden=true;el.toolsMenu.hidden=true;if(activeView==='history')showView('conversation');});
  document.addEventListener('pointerdown',e=>{const target=e.target;if(!el.toolsMenu.hidden&&!target.closest('.tools-anchor')){el.toolsMenu.hidden=true;el.toolsButton.setAttribute('aria-expanded','false');}if(!el.headerMenu.hidden&&!el.headerMenu.contains(target)&&!el.moreButton.contains(target))el.headerMenu.hidden=true;});
  window.addEventListener('message',event=>{const m=event.data;if(m?.type==='state')renderState(m.state);if(m?.type==='busy'){if(!m.value)agentActive=false;setBusy(!!m.value);}if(m?.type==='streamStart'){el.conversation.querySelector('.empty-state')?.remove();el.conversation.append(messageNode('user',m.prompt,new Date().toISOString()));const article=node('article',undefined,'message assistant');streamingContent=node('div',undefined,'content');streamingContent.append(node('span','Thinking…','thinking-placeholder'));article.append(streamingContent);el.conversation.append(article);streamingText='';el.workingLabel.textContent='Thinking…';if(stickToBottom)el.conversation.scrollTop=el.conversation.scrollHeight;}if(m?.type==='streamChunk'&&streamingContent){streamingText+=m.chunk;streamingContent.replaceChildren(renderMarkdown(streamingText));if(stickToBottom)el.conversation.scrollTop=el.conversation.scrollHeight;}if(m?.type==='notice'){el.errorText.textContent=m.message;el.errorBanner.classList.add('notice');el.errorBanner.hidden=false;el.retry.hidden=true;el.composerStatus.classList.remove('error');setBusy(false);}if(m?.type==='error'){el.errorText.textContent=m.message;el.errorBanner.classList.remove('notice');el.errorBanner.hidden=false;el.retry.hidden=false;el.composerStatus.classList.add('error');if(streamingContent&&!streamingText){streamingContent.replaceChildren(node('span',m.message,'error-text'));streamingContent=undefined;}setBusy(false);}if(m?.type==='agentReset'){agentActive=true;setBusy(true);el.agentActivity.replaceChildren();el.agentActivity.hidden=false;el.changedFiles.replaceChildren();el.changedFiles.hidden=true;}if(m?.type==='agentActivity'){el.agentActivity.hidden=false;el.workingLabel.textContent=m.activity.label;el.agentActivity.replaceChildren();const item=node('div',undefined,'activity-item '+m.activity.status);item.append(node('span',m.activity.status==='running'?'•':m.activity.status==='complete'?'✓':m.activity.status==='cancelled'?'■':'!','activity-marker'),node('span',m.activity.label,'truncate'));el.agentActivity.append(item);}if(m?.type==='changedFiles'){el.changedFiles.hidden=false;el.changedFiles.replaceChildren(node('strong','Changed Files'));for(const file of m.files)el.changedFiles.append(node('div',`${file.status}  ${file.path}`,'changed-file truncate'));}if(m?.type==='agentComplete'){if(m.status==='complete')setTimeout(()=>{el.agentActivity.replaceChildren();el.agentActivity.hidden=true;},700);}if(m?.type==='contextState'){state.contexts=m.contexts||[];renderOptions();}if(m?.type==='webSearchState'){state.webSearch=!!m.enabled;renderOptions();}if(m?.type==='agentStopped'){agentActive=false;setBusy(false);}if(m?.type==='showHistory')showView('history');});
  autoGrow();post('ready');
})();
